import Head from "next/head";
import Header from "./components/Header";
import Footer from "./components/Footer";

export default function Home() {
  const users = ["Ahmet", "Mehmet", "Ali", "Veli"];
  const animals = ["Kedi", "Köpek", "Fare", "Yılan"];
  return (
    <>
      <Head>
        <title>Conponent Mantık</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header systemUsers={users} />
      <Footer gonderilecekHayvan={animals} />
    </>
  );
}
